# bind game to 27632 port to get serverlist
# required to get serverlist from gameranger + SNAT server (without server files modification)
# option is restricting one game instance per computer, not required when server has removed serverlist broadcasting
# remove option or set to -1 to disable it
# use it only when server in `known_servers` requires it to display serverlist
# uncomment next line to enable:
# bind_to_port = 27632


# change FOV (in degrees), game by default use 46.8 degrees FOV
# to set FOV uncomment `fov = 60.0` and replace 60.0 with FOV you want
# fov = 60.0


ping_display = 'colored_numbers' # 'default' or 'numbers' or 'colored_numbers'

# to disable KD mod, comment out or remove at least one option `stats_column_1` or stats_column_2`
stats_column_1 = 'accuracy' # 'kills' or 'deaths' or 'accuracy' or 'kd_balance' or 'kd_ratio'
stats_column_2 = 'kd_ratio' # 'kills' or 'deaths' or 'accuracy' or 'kd_balance' or 'kd_ratio'


# known server list in format <ip>:<port>
# example:
# known_servers = [
#     "12.34.56.78:27632",
#     "10.10.10.10:27631"
# ]
known_servers = [
    "51.77.58.210:27632",
    "51.77.58.210:27633",
    "51.77.58.210:27634",
    "51.77.58.210:27635",
    "147.185.221.16:65516",
    "51.77.44.173:27632",
    "51.77.44.173:27633",
    "51.77.44.173:27634",
    "51.77.44.173:27635",
    "51.77.44.173:27636",
    "185.204.170.236:27632",
    "37.32.27.14:27632",
    "151.241.226.70:27632",
    "94.101.187.150:27632",
    "131.108.143.166:27632",
]
